### PR TITLE
Feature/updatetables/crystalc

### PR DESCRIPTION
**Pull request by crystal-csete**
Now the saved cases and saved judges pages are the same for styles.
Cleaned up the CSS files.

### CODE REVIEW

**Review by c-melchor — APPROVED** [review]
Nice job on the update, excited to see changes.

**Review by ndossett — APPROVED** [review]
I appreciate you for doing all of this style refactoring work. It's tedious, but will make our app so much more readable for the next unit!

**Review by ruizaj13 — APPROVED** [review]
A neat codebase is a good codebase, nice job

**Review by JusticeMatthew — APPROVED** [review]
Thank your for all the hard work unifying the styles

**Review by aydinsenih — APPROVED** [review]
looks good

**Pull request merged**
