### PR TITLE
FAQ database integration and admin tools styling

### PR DESCRIPTION
**Pull request by reesharper**

### CODE REVIEW

**Review by c-melchor — APPROVED** [review]
Nice job making the FAQs functional.

**Review by JusticeMatthew — APPROVED** [review]
Looks good

**Review by ruizaj13 — APPROVED** [review]
Awesome work!

**Review by crystal-csete — APPROVED** [review]
This looks good to me, great addition.

**Review by cmirza — COMMENTED** [review]
Lets go!

**Pull request merged**
