### PR TITLE
I did a major overhaul of CSS in the judge page and judge table

### PR DESCRIPTION
**Pull request by crystal-csete**
I put the existing CSS for judge page/table into CSS Component files. I added a CSS file for judge Table page also.

### CODE REVIEW

**Review by c-melchor — APPROVED** [review]
I approve these changes, it'll be nice to have everything sorted into their own files.

**Review by JusticeMatthew — APPROVED** [review]
I like the separation of concerns, breaking all the styling out into its own file. Good stuff

**Review by ruizaj13 — APPROVED** [review]
This ensures we keep a clean and organized codebase, good job.

**Review by reesharper — APPROVED** [review]
Styles look amazing! This is so important!

**Review by cmirza — APPROVED** [review]
Great to see the styling continue to evolve and improve!

**Pull request merged**
