### PR TITLE
adjusted filter bar and individual filter.

### PR DESCRIPTION
**Pull request by willmoon19**
Co-authored-by: Cory Scofield <ctscofield@gmail.com>

[Trello](https://trello.com/c/S2Qtb9jG)
[Loom](https://www.loom.com/share/ac77bea7a45b4de4b24beeb393e13415)

## Description

Made the filter bar more intuitive by moving it away from the save checkboxes. updated UI of the filter box and the filters themselves, making them much more visible when added as well as making the "X" (delete) button on on the individual filters more distinct.

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have removed unnecessary comments/console logs from my code
- [x] My changes generate no new warnings
- [x] I have checked my code and corrected any misspellings
- [x] No duplicate code left within changed files
- [x] Size of pull request kept to a minimum
- [x] Pull request description clearly describes changes made & motivations for said changes

### CODE REVIEW

**Review by ctscofield — APPROVED** [review]
A solid amount of changes here! The new styling and Filter keyword correction look great and that's something that has been needing to happen!

**Review by leecrowe — APPROVED** [review]
Awesome changes, the end result of that looks super clean and readable. Well done you two!

**Review by Vehmeyer — APPROVED** [review]
Nice improvement! This makes it easier to use the filters, and as you said, "more intuitive". Good work on this!

**Comment by mariuscmoldovan** [comment]
Nice visual improvement. Good job!

**Review by mariuscmoldovan — APPROVED** [review]

**Comment by RasmussenBen** [comment]
These changes look great! I appreciate the use of existing branding colors to keep the styling uniform. Also, the X button to clear specific filters is a great UX change. These small changes can go a long way!

**Review by RasmussenBen — APPROVED** [review]

**Review by ivan-mihailov — APPROVED** [review]
Loom video walking through the changes was very helpful. Great visual improvement to the Filter function that makes it clearer to the user and allows it to standout better. Clean code. Great Job!

**Review by sirakisaias — APPROVED** [review]
The addition of **filter** to the case and judge page with different color and new added styles looks good. And walking us through on the loom video gives more clear message on what you did. Great job.

**Pull request merged**
