### PR TITLE
refactored the style on the side drawer.

### PR DESCRIPTION
**Pull request by willmoon19**
Co-authored-by: Cory Scofield <ctscofield@gmail.com>

[Trello](https://trello.com/c/OWNdGA8N)
[Loom](https://www.loom.com/share/844843c9e3ad48a3862fc0782d3359e7)
Video will help make this more clear

## Description
I added this commit to the original branch I was working on and it got pushed to main without getting approved. I am making this pull request so we can all see the changes and to make a record of them.
Added new styling to the Side Drawer component. Got rid of the absolute position and the bottom styling on the .collapseButton on line 198.
changed styles of the icons from lines 31 - 87, adjusting the left styling pixel sizes from 26px to 31px on line 32 and 35 and then changing the left styling of lines 41 - 74 from 20px to 26px. Also adjusted each words padding on the side Drawer, in order to space them out properly.

Fixes # (issue)
centering on the side drawer

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have removed unnecessary comments/console logs from my code
- [x] My changes generate no new warnings
- [x] I have checked my code and corrected any misspellings
- [x] No duplicate code left within changed files
- [x] Size of pull request kept to a minimum
- [x] Pull request description clearly describes changes made & motivations for said changes

### CODE REVIEW

**Review by ctscofield — APPROVED** [review]

**Review by mathewmahoneyds20 — APPROVED** [review]
Yet more little fixes that make a huge difference to the sites functionality and its cohesiveness.  I saw your initial presentation when you made the changes and after reading your fix I give a thumbs up and a good job!

**Comment by Vehmeyer** [comment]
Nice work! This is a good UX enhancement for end users. I watched the Product Review video where Frank offered some suggestions to implement a few finishing touches to enhance the functionality (such as centering the icons, etc). Great work on implementing that feedback!

**Review by Vehmeyer — APPROVED** [review]
Nice work! This is a good UX enhancement for end users. I watched the Product Review video where Frank offered some suggestions to implement a few finishing touches to enhance the functionality (such as centering the icons, etc). Great work on implementing that feedback!

**Review by RasmussenBen — APPROVED** [review]
Thanks, Will. Appreciate you putting in the extra work to discuss these changes even though they already made their way into Main. Good UI changes with clear rationale explained in the Loom video.

**Review by ivan-mihailov — APPROVED** [review]
The Loom video was super helpful. Showed the previously merged PR and why this PR was necessary. The changes to the side drawer look great--much more user-friendly and professional-looking. Great Job!

**Review by AZICO — APPROVED** [review]
Your detailed and clear explanation is highly appreciated. Great changes to the UI/UX design.

**Pull request merged**
