### PR TITLE
fixed a bug in pendingUsers.js

### PR DESCRIPTION
**Pull request by DanielBrannon**
## Description
Pending Users was not updating to the database correctly because someone put an axios.post instead of axios.put.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have removed unnecessary comments/console logs from my code
- [x] I have made corresponding changes to the documentation if necessary (optional)
- [x] My changes generate no new warnings
- [x] I have checked my code and corrected any misspellings
- [x] No duplicate code left within changed files
- [x] Size of pull request kept to a minimum
- [x] Pull request description clearly describes changes made & motivations for said changes

### CODE REVIEW

**Review by Humza23 — CHANGES_REQUESTED** [review]
I see the package-lock.json was deleted in your changes. Please review this

**Comment by drslaughterrex** [comment]
Agree with Humza, that's concerning.

**Comment by DanielBrannon** [comment]
> I see the package-lock.json was deleted in your changes. Please review this

I deleted it on purpose

**Comment by Humza23** [comment]
> > I see the package-lock.json was deleted in your changes. Please review this
> 
> I deleted it on purpose

Why was it deleted on purpose? A bit unclear

**Comment by DanielBrannon** [comment]
> > > I see the package-lock.json was deleted in your changes. Please review this
> > 
> > 
> > I deleted it on purpose
> 
> Why was it deleted on purpose? A bit unclear

I deleted it because I changed a single line of code, I wanted to be sure I didn't change 15,000 lines of code in package.json over literally 1 change. It was unnecessary

**Pull request closed without merging**
