### PR TITLE
first panel defaults to open, panels also close when another is opened

### PR DESCRIPTION
**Pull request by ruizaj13**
Minor FAQ tweaks

### CODE REVIEW

**Review by cmirza — APPROVED** [review]
Accordion effect, nice!

**Review by c-melchor — APPROVED** [review]
It’ll be nice to have that effect for better UX.

**Review by JusticeMatthew — APPROVED** [review]
Thank you for those adjustments! Should provide a clear path for the user :)

**Review by ndossett — APPROVED** [review]
This should make the page easier to navigate for the users. The accordion effect is visually appealing - nice job

**Review by crystal-csete — APPROVED** [review]
Users will like this accordion effect.

**Pull request merged**
