### PR TITLE
Feature/judge table filter chip removal

### PR DESCRIPTION
**Pull request by AD9018**
## Description

This fix addresses the Judge Table but specifically the ability for a user to be able to remove the filter chip just like the Case Table.
We are not getting any JSON strings either. We still need to implement multi-search functionality and the ability to search for the date as well just as Case Table does.  

Co-Authored-by: Ricky Klusmeier

Fixes # (issue)
Addressed User constraints, gives us the ability to circumvent directly using the ANT search component.

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have removed unnecessary comments/console logs from my code
- [x] My changes generate no new warnings
- [x] I have checked my code and corrected any misspellings
- [x] No duplicate code left within changed files
- [x] Size of pull request kept to a minimum
- [x] Pull request description clearly describes changes made & motivations for said changes
https://www.loom.com/share/848c28b622ae49e08430c19b579db6c4

### CODE REVIEW

**Comment by AD9018** [comment]
Please excuse any code cleanup that may have to be done, this was done in a later pull which should not cause any issues. There are 2 consecutive pull requests after this where the 3rd one is just cleanup as well as enabling a better search functionality when it comes to multiple searches.

**Review by lucaschatham — APPROVED** [review]
Agreed. Adding that multi-functionality feature would be cool. Other than a link to a Trello ticket, this looks great. Solid work.

**Review by zunerabokhari — APPROVED** [review]
this seems like a useful feature to have. Being from the DS side, I appreciate you showing the actual feature in action in your video as I may not have otherwise fully understood the code.

**Review by prodhc — APPROVED** [review]
Great work on this ticket! A decent amount of code was added compared to some other PRs but the loom video does a great job explaining it all.

**Review by ctscofield — APPROVED** [review]
I really appreciate you guiding us through your code and showing us the similarities to the case table for removal and state management. You are doing great work! keep it up!

**Pull request merged**
