### PR TITLE
Feature/updatetables/crystalc

### PR DESCRIPTION
**Pull request by crystal-csete**

### CODE REVIEW

**Review by JusticeMatthew — APPROVED** [review]
I have previewed these changes and they look great!

Thanks for dealing with the package lock!

**Review by ndossett — APPROVED** [review]
Files look nice and clean. Thanks for helping to streamline the app design!

**Review by c-melchor — APPROVED** [review]
Exciting changes and organization to these files, nice job!

**Review by cmirza — APPROVED** [review]
These updates look great, looking forward to the updated design.

**Pull request merged**
