### PR TITLE
Another Round of UI changes

### PR DESCRIPTION
**Pull request by drslaughterrex**
## Description

Removed the orange image used as a divider and replaced them with a small 1px orange line. Much of the centering was off with a number of pages so that is fixed as well to make them more uniform.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have removed unnecessary comments/console logs from my code
- [x] I have made corresponding changes to the documentation if necessary (optional)
- [x] My changes generate no new warnings
- [x] I have checked my code and corrected any misspellings
- [x] No duplicate code left within changed files
- [x] Size of pull request kept to a minimum
- [x] Pull request description clearly describes changes made & motivations for said changes

### CODE REVIEW

**Comment by drslaughterrex** [comment]
The only changes that remain are to the Admin-specific pages and the Support page.

**Comment by DanielBrannon** [comment]
Can we get a snippet of what the new interface looks like?

**Review by DanielBrannon — APPROVED** [review]
Looks good

**Comment by DanielBrannon** [comment]
make sure to resolve the merge conflicts though

**Review by Gavin-Rilee — APPROVED** [review]

**Review by AlexTran0899 — APPROVED** [review]

**Pull request merged**
