### PR TITLE
Feature/checkbox grid/niki d

### PR DESCRIPTION
**Pull request by ndossett**

### CODE REVIEW

**Review by c-melchor — APPROVED** [review]
Approved, this change will make our styling more cohesive with the primary HRF site.

**Review by JusticeMatthew — APPROVED** [review]
A nice clean fix for those colors, good work

**Review by ruizaj13 — APPROVED** [review]
Important change to keep the application looking cohesive and polished, nice job

**Review by crystal-csete — APPROVED** [review]
This color will match and look great overall.

**Pull request merged**
