### PR TITLE
submit button styling fix

### PR DESCRIPTION
**Pull request by ruizaj13**

### CODE REVIEW

**Review by JusticeMatthew — APPROVED** [review]
Ty ty

**Review by reesharper — APPROVED** [review]
Nice catch! this will look much better!

**Review by c-melchor — APPROVED** [review]
Thanks, Juan! Looks great

**Review by crystal-csete — APPROVED** [review]
This fix for the button color looks good to me!

**Review by cmirza — APPROVED** [review]
This update should look good

**Pull request merged**
