### PR TITLE
added styling to account page and css file

### PR DESCRIPTION
**Pull request by crystal-csete**
Added a CSS file to account component.
Added Ant Design to the account component.

### CODE REVIEW

**Review by c-melchor — APPROVED** [review]
Nice job, Crystal!

**Review by ndossett — APPROVED** [review]
Love these finishing touches to styling!

**Review by reesharper — APPROVED** [review]
Looks great! love that we are taking out the MUI makeStyles. Wish I thought of that when building these components out.

**Review by JusticeMatthew — APPROVED** [review]
Love me some styling!

**Review by ruizaj13 — APPROVED** [review]
Nice job with the ant design conversions

**Pull request merged**
