### PR TITLE
updates styles for tabs, cleans up code

### PR DESCRIPTION
**Pull request by c-melchor**
- Tabs were moved inside table yesterday
- This code styles them to fit the table aesthetic
- Got rid of unnecessary code

https://user-images.githubusercontent.com/71955286/116295893-7066b900-a74e-11eb-823e-4dc1ecbfa837.mov

### CODE REVIEW

**Review by ruizaj13 — APPROVED** [review]
Looks great and the video preview is an awesome touch!

**Review by ndossett — APPROVED** [review]
I didn't know we could leave video previews on here! Great job turning around this request from the design manager so quickly.

**Review by cmirza — APPROVED** [review]
Changes look good, having video previews of the changes is super convenient.

**Review by crystal-csete — APPROVED** [review]
This is a good fix, the code looks clean!

**Pull request merged**
