### PR TITLE
fixed bug so judge page works now

### PR DESCRIPTION
**Pull request by crystal-csete**

### CODE REVIEW

**Review by JusticeMatthew — APPROVED** [review]
Ty for fixing the judge page

**Review by c-melchor — APPROVED** [review]
Nice find, I'm glad judges will be able to render for better user experience.

**Review by aydinsenih — APPROVED** [review]
clean fix good job

**Review by cmirza — APPROVED** [review]
Good catch, glad to see this fix

**Review by ruizaj13 — APPROVED** [review]
Good catch, one step closer to an mvp

**Pull request merged**
