### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by zunerabokhari**
Adding the data flow diagram for the frontend to have a clear understanding of the flow of data through the app.

### CODE REVIEW

**Review by AD9018 — APPROVED** [review]
Look great, seems like simple changes. Commenting for commenting. :)

**Review by matthewblackbu — APPROVED** [review]
I love the new flow dataflow chart it looks so much better than the old one

**Comment by Vehmeyer** [comment]
Looks great. This is a helpful addition to understand how the data flows.

**Review by willmoon19 — APPROVED** [review]
Having the data flow ready and available is a great idea! This is a small but important addition that really makes things easier for new people coming in. Great work!

**Pull request merged**
