### PR TITLE
All menus match now. Put CSS into their own files. Took out MUI and added Ant Design.

### PR DESCRIPTION
**Pull request by crystal-csete**

### CODE REVIEW

**Review by c-melchor — APPROVED** [review]
This is great, nice job cleaning up the code and putting styles in their own files.

**Review by ndossett — APPROVED** [review]
Thank you for this tedious work. It makes the components look cleaner and will be easier for then next team to make changes

**Review by ruizaj13 — APPROVED** [review]

**Comment by ruizaj13** [comment]
Great work, this'll help keep the codebase more organized

**Review by JusticeMatthew — APPROVED** [review]
More separation of concerns, I like it 👍

**Review by aydinsenih — APPROVED** [review]
nice styling. good work

**Pull request merged**
