### PR TITLE
resubmitted PR without package lock

### PR DESCRIPTION
**Pull request by ruizaj13**
FAQ PR Part 2: Electric Boogaloo

Please feel free to suggest any language changes or any other questions that should be added.

Rather than display them plainly the questions are displayed as collapsing panels (using antd) which expand to reveal the answer to the question. Figured it looked more polished that way.

### CODE REVIEW

**Review by JusticeMatthew — APPROVED** [review]
Thank you Juan!

I especially like the security-related questions! Super important thing to highlight!

**Review by crystal-csete — APPROVED** [review]
These will make the Q & A page look full and nice.

**Review by ndossett — APPROVED** [review]
Love the collapsing component!

**Review by reesharper — APPROVED** [review]
This looks great to me! I used this to make the seed data for the FAQ table since this will migrate to an endpoint. Thank you!

**Pull request merged**
