### PR TITLE
created all managerial tools for the FAQ feature

### PR DESCRIPTION
**Pull request by reesharper**

### CODE REVIEW

**Review by ruizaj13 — APPROVED** [review]
New feature looks awesome, glad to see everything coming together

**Review by crystal-csete — APPROVED** [review]
This will be a great interactive feature for the user to navigate through the site.

**Review by JusticeMatthew — APPROVED** [review]
I never even considered this user story as being needed :O good catch!

Great work

**Review by ndossett — APPROVED** [review]
Looks good. Nice feature that will help admin manage the app more effectively as time goes on.

**Pull request merged**
