### PR TITLE
Bug/home styling adjustment

### PR DESCRIPTION
**Pull request by Fabian-Gorka**
## Description
fixxed graph home styling to align witht he rest of the app
https://www.loom.com/share/8e575a32ca234aa390cfac008805c03d

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have removed unnecessary comments/console logs from my code
- [x] I have made corresponding changes to the documentation if necessary (optional)
- [x] My changes generate no new warnings
- [x] I have checked my code and corrected any misspellings
- [x] No duplicate code left within changed files
- [x] Size of pull request kept to a minimum
- [x] Pull request description clearly describes changes made & motivations for said changes

### CODE REVIEW

**Review by Spencerp34 — APPROVED** [review]
This is a small change, but makes an aesthetic difference for sure! The structure is better!

**Review by wzd200 — APPROVED** [review]
Less whitespace and more centered content definitely makes it look better. Great work.

**Review by sirakisaias — APPROVED** [review]
The changes made looks really good, catching these small bugs and fixing it are important. The code looks great and clean.

**Review by paulstgermain — APPROVED** [review]
Approving on the basis of it being a good fix, to clean up open PRs/branches, and test assignees for API.

**Pull request merged**
