### PR TITLE
User can edit a case from the individual case card.

### PR DESCRIPTION
**Pull request by aydinsenih**
moment.js library added to manage ant design datePicker.

JWT token fix for CaseOverview and CaseUpdate.

### CODE REVIEW

**Review by c-melchor — CHANGES_REQUESTED** [review]
It looks good overall. 👍  Some minor changes: since we aren't using useHistory in CaseOverview anymore, we should probably remove that. Also, this PR includes package.json, this should be removed before merge.

**Review by ndossett — APPROVED** [review]
Looks good - great to have another item checked off the trello board. Kudos for using antd for styling!

**Review by crystal-csete — APPROVED** [review]
Great job on this addition, we needed this functionality for this component.

**Comment by JusticeMatthew** [comment]
> It looks good overall. 👍 Some minor changes: since we aren't using useHistory in CaseOverview anymore, we should probably remove that. Also, this PR includes package.json, this should be removed before merge.

Agreed

**Review by ruizaj13 — APPROVED** [review]
Added necessary functionality and cleaned up the codebase in the process, awesome job

**Review by JusticeMatthew — APPROVED** [review]
Good work on the case editing, looking like it will be more and more a necessary feature.

Everyone else don't forget to install the new dependency

**Review by c-melchor — APPROVED** [review]
Looks good.

**Pull request merged**
