### PR TITLE
Added collapsing feature to side drawer

### PR DESCRIPTION
**Pull request by willmoon19**
## Description

Added a button that collapses the side drawer leaving the icons there for the user to see as well as giving them more space

Co-Authored-by: @ctscofield 

[Trello](https://trello.com/c/RogihNTZ)
[Loom](https://www.loom.com/share/9ee8eea1f2174ec282f1abefa1f48305)

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have removed unnecessary comments/console logs from my code
- [x] My changes generate no new warnings
- [x] I have checked my code and corrected any misspellings
- [x] No duplicate code left within changed files
- [x] Size of pull request kept to a minimum
- [x] Pull request description clearly describes changes made & motivations for said changes

### CODE REVIEW

**Review by RickyKlusmeier — APPROVED** [review]
Looks good and will be nice that it can be collapsible now.

**Review by zunerabokhari — APPROVED** [review]
Looks like a nice addition to make the page look more clean and sleek. I like the little detail of the left/right arrow button. nice job!

**Review by leecrowe — APPROVED** [review]
I think that's an awesome addition, it looks super clean and like it functions well. Awesome work guys!

**Review by ctscofield — APPROVED** [review]
Changes are nice and clean make for a really cool feature, keep up the great work!

**Review by schandrupatla — APPROVED** [review]
Good addition, it makes the page neat now. Your video explanation was also very clear showing changes made and also code changes

**Review by AD9018 — APPROVED** [review]
Great functionality and makes for a better User experience.

**Review by matthewblackbu — APPROVED** [review]
I love how this looks you did a great job once again will

**Pull request merged**
