### PR TITLE
Bugfix/judge names

### PR DESCRIPTION
**Pull request by jenna-anderson**
## Description

Judge names were not showing on the case table or in case details and if a user saved a case or judge it would cause an error in the backend and an infinite loading wheel, requiring a server restart. The bulk of this fix is in the corresponding [backend PR](https://github.com/Lambda-School-Labs/human-rights-first-asylum-be-a/pull/172). Since the backend will no longer be sending multiple judges for a case after dropping appellate cases (discussed with the stakeholder since initial cases (one judge per case) will be the primary case type in production), changing judge_name in the case table to just a concatenation of the first_name, middle_initial, and last_name of the single judge sent to the frontend, displays the judge name correctly. 

An additional patch was added to this PR, changing filed_within_year to check_for_one_year and date to decision_date and type_of_violence to type_of_persecution. These variables were changed in a previous PR to match what the backend was sending but were overwritten during a separate PR resolution of merge conflicts. These old variable names were causing these variables to not appear in the case table on the frontend, and updating them resolved this issue.

[Trello Card](https://trello.com/c/vgdJxyz4)

[Loom Video](https://www.loom.com/share/5b5c51fe3850499f91c613bfc40379b1?sharedAppSource=personal_library)

Fixes judge names not appearing on the case table or case details.
Also fixes Filed Within One Year and Persecution Experienced variables not appearing in the case table.

## Type of change

Please delete options that are not relevant.

- [X] Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have removed unnecessary comments/console logs from my code
- [ ] I have made corresponding changes to the documentation if necessary (optional)
- [X] My changes generate no new warnings
- [X] I have checked my code and corrected any misspellings
- [X] No duplicate code left within changed files
- [X] Size of pull request kept to a minimum
- [X] Pull request description clearly describes changes made & motivations for said changes

### CODE REVIEW

**Review by joshuascan — APPROVED** [review]
This is a great fix! It will be nice to have the full and complete case table when working on other branches. And good catch with those variable names that were reverted back to a previous state. That could have cause a headache had those gone unnoticed.

**Review by prodhc — APPROVED** [review]
Great job catching the merge error and fixing the variable names! The old code from lines 98-112 in caseTable.js looked like a mess so it's nice to have it replaced with a single line of code. I know the bulk of the fix was done on the backend but the infinite loading wheel bug was quite annoying so thank you for taking care of that on both ends.

**Review by ZacharyCooremans — APPROVED** [review]
Amazing fixes going on between the front end and the backend to display judge names. This will definingly help fix other parts of the project. Great video explaining what you did and why.

**Review by chrisjs87 — APPROVED** [review]
Good job on identifying the issue! Glad to see you identified that the date/decision_date and type of violence/type of persecution  as well as credible/credibility were part of the problem! I also liked the verbiage change for the title: 'Filed within Year' change --> title: 'Filed within One Year'
Again, great job!

**Review by schandrupatla — APPROVED** [review]
Good work ! Thank you for taking care of variables renaming that occurred due to merge conflicts. Hopefully, this should be fixed for good now.

**Pull request merged**
