### PR TITLE
Feature/judge table date bug fix

### PR DESCRIPTION
**Pull request by AD9018**
## Description

This issue takes care of rendering results for the date search in the Judges table. 

Fixes # (issue)
Before the user was not able to render search results for the date.

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have removed unnecessary comments/console logs from my code
- [ ] I have made corresponding changes to the documentation if necessary (optional)
- [x] My changes generate no new warnings
- [x] I have checked my code and corrected any misspellings
- [x] No duplicate code left within changed files
- [x] Size of pull request kept to a minimum
- [x] Pull request description clearly describes changes made & motivations for said changes

### CODE REVIEW

**Review by leecrowe — APPROVED** [review]
Although I don't fully know what's being changed it looks like you refactored and added quite a few  useful points, nice job

**Review by ctscofield — APPROVED** [review]
Lots of great changes in here! In addition to fixing the search filter feature you also greatly improved the readability of these files and cleaned them up a lot!

**Review by willmoon19 — CHANGES_REQUESTED** [review]
Overall you are moving some code around, If you could explain your reasoning behind that, I think that would really clear things up. The only real change I see is on line 153. The explanation for it at the bottom of the file should be added to the description of the pull request and deleted from the code itself. With a video showing how it works and those changes implemented I believe this would be perfect.

*delete comments at the bottom of both files
*add them into the details of the changes in the pull request

**Comment by EmilyAFlener** [comment]
test test

**Review by EmilyAFlener — APPROVED** [review]
testtest

**Review by ivan-mihailov — APPROVED** [review]
Even though I am not familiar with Javascript, the code looks clean and it solves a bug that is important to fix. Good Job!

**Review by AZICO — COMMENTED** [review]
I notice you have added the '*' sign on line 13 but haven't seen an explanation of what does it do to the code.

**Pull request merged**
