### PR TITLE
table mostly updated with re-named and added columns

### PR DESCRIPTION
**Pull request by Dionne-Stratton**
All columns have been re-named or added and reordered to conform to the new list. To be changed still: case id and judge name as they are more difficult to do.

### CODE REVIEW

**Review by reesharper — CHANGES_REQUESTED** [review]
Since I had to reset the package-lock there are some conflicts on this that can't be resolved on Github. Can you pull from main and deny any changes from your branch in the package-lock file?

**Review by kristapants — COMMENTED** [review]
_field: 'id', //difficult, do last_  This and the Judge Name field incomplete per inline comments. Noted here for visibility. 

  src/components/pages/CaseTable/CaseTable.js line 205, misspelled applicant.

What are the package lock changes? There are 30,000 deletions, are those meant to be included in this PR?

**Review by reesharper — APPROVED** [review]
Love these changes, naming conventions can be tedious and you killed it!

**Comment by reesharper** [comment]
> _field: 'id', //difficult, do last_ This and the Judge Name field incomplete per inline comments. Noted here for visibility.
> 
>   src/components/pages/CaseTable/CaseTable.js line 205, misspelled applicant.
> 
> What are the package lock changes? There are 30,000 deletions, are those meant to be included in this PR?

We fixed the package-lock issues, I had to regenerate the package-lock to fix deployment while she was working on this branch, so we just resolved the merge conflicts locally.

**Review by kristapants — APPROVED** [review]
Applicant wasn't misspelled. Was a removed line. I approve the name changes and added columns to align with the stakeholders request.

**Pull request merged**
