### PR TITLE
Feature/support page faq edit

### PR DESCRIPTION
**Pull request by bukit3point0**
## Description

The Support page was titled as FAQ. This page will have multiple different support topics, and needed to be seen as such.
As this is the only page currently on the site that will have this layout, I have presented a suggestion on layout. The title 'Support' is still the same size and layout as the titles on other pages, but FAQ is now dropped down underneath the divider bar and is at 1.5rem versus the main titles of 1.8rem.

Fixes # (issue)
'Support' is now the main title, FAQ is a subtitle.

## Type of change

Please delete options that are not relevant.

- [X] New feature (non-breaking change which adds functionality)

## Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have removed unnecessary comments/console logs from my code
- [X] My changes generate no new warnings
- [X] I have checked my code and corrected any misspellings
- [X] No duplicate code left within changed files
- [X] Size of pull request kept to a minimum
- [X] Pull request description clearly describes changes made & motivations for said changes

### CODE REVIEW

**Review by salvare736 — APPROVED** [review]
I was thrown off at first because the lion's share of this PR involves the refactoring of the role_id property throughout the frontend, whereas the description of the PR only mentions the changes to the Support/FAQ page. Regardless, the changes themselves look great. Good work!

**Comment by salvare736** [comment]
By the way, I noticed that this update removes almost 33-thousand lines of code while adding just under 400. I just want to make sure if that was intentional or not. The removed lines seem to be mostly from the package-lock.json.

**Review by n0tybynature — APPROVED** [review]
Good changes to me and it looks fine.

**Comment by bukit3point0** [comment]
> I was thrown off at first because the lion's share of this PR involves the refactoring of the role_id property throughout the frontend, whereas the description of the PR only mentions the changes to the Support/FAQ page.

It seems I made an error when creating the branch - there was another PR I created with the role changes, but I must have created the branch from there rather than main.

**Pull request merged**
