### PR TITLE
adding more questions and answers to the support page

### PR DESCRIPTION
**Pull request by ruizaj13**
Please feel free to suggest any language changes or any other questions that should be added. 

Rather than display them plainly the questions are displayed as collapsing panels (using antd) which expand to reveal the answer to the question. Figured it looked more polished that way.

### CODE REVIEW

**Review by c-melchor — APPROVED** [review]
Not sure if the commented out code at the bottom is still needed? Other than that looks good to me.

**Review by reesharper — APPROVED** [review]
Love the questions you came up with, this looks great!

**Comment by ruizaj13** [comment]
> Not sure if the commented out code at the bottom is still needed? Other than that looks good to me.

Totally forgot I left that commented out code on the bottom but I'll be sure to remove that when I get home, good catch Christina!

**Review by ndossett — APPROVED** [review]
Nice use of the collapse feature!

**Review by JusticeMatthew — CHANGES_REQUESTED** [review]
Please resubmit this pull request without your package.json

DO NOT DELETE IT STRAIGHT FROM THE PULL 
Github thinks this ^^^ means "delete it from the whole repo" :(  

Thank you!

**Pull request closed without merging**
