### PR TITLE
Changed header color, Upload button color, and logo img

### PR DESCRIPTION
**Pull request by drslaughterrex**
## Description

The team decided that the header being white was too much on the user's eyes, so I've changed it to the project's Blue (#2a5c8d) while changing the "Upload" button to the Orange color (#ff7f0e), followed by adding the white text logo to replace the blue text one.

PR2

## Type of change

Please delete options that are not relevant.

- [ x ] Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [ x ] My code follows the style guidelines of this project
- [ x ] I have performed a self-review of my own code
- [ x ] I have removed unnecessary comments/console logs from my code
- [ x ] I have made corresponding changes to the documentation if necessary (optional)
- [ x ] My changes generate no new warnings
- [ x ] I have checked my code and corrected any misspellings
- [ x ] No duplicate code left within changed files
- [ x ] Size of pull request kept to a minimum
- [ x ] Pull request description clearly describes changes made & motivations for said changes

### CODE REVIEW

**Review by Humza23 — APPROVED** [review]
Well done! Great changes to the visuals of major points of the application!

**Review by dancingheart714 — APPROVED** [review]
This looks great!  I'm really glad we decided to do it, I think it looks so much better.  Did you try removing the shadow? I know we talked about it.

**Comment by CrashOverride1987** [comment]
Logo seems a tad small

**Comment by drslaughterrex** [comment]
> This looks great! I'm really glad we decided to do it, I think it looks so much better. Did you try removing the shadow? I know we talked about it.

I'll be looking into this in the near future while looking into the logo!

**Pull request merged**
