### PR TITLE
added multiline to FAQ forms, also made contact form match the patter…

### PR DESCRIPTION
**Pull request by reesharper**
…n used in the rest of the app, lastly finished functionality of the contact form

### CODE REVIEW

**Review by JusticeMatthew — APPROVED** [review]
I am pleased with these changes

**Review by c-melchor — APPROVED** [review]
Awesome work

**Review by crystal-csete — APPROVED** [review]
This will look nice for the user.

**Review by ndossett — APPROVED** [review]
Nice finishing touches that will improve the look of the page.

**Review by ruizaj13 — APPROVED** [review]
Nice job adding contact form functionality

**Pull request merged**
