### PR TITLE
Feature/logo shrink

### PR DESCRIPTION
**Pull request by bukit3point0**
## Description

The logo in the header was a tad on the large size. It has been changed from a height of 62px to 50px, which matches better with the other components in line. The top bar had a flex, but I added an align-items: center so that the logo was level with the other side.

Fixes # (issue)
MainHeader.less file has had two lines changed to reflect the logo change; the header is now aligned center to ensure the logo stays in the center of the div

## Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have removed unnecessary comments/console logs from my code
- [X] My changes generate no new warnings
- [X] I have checked my code and corrected any misspellings
- [X] No duplicate code left within changed files
- [X] Size of pull request kept to a minimum
- [X] Pull request description clearly describes changes made & motivations for said changes

### CODE REVIEW

**Review by salvare736 — APPROVED** [review]
Looks good!

**Review by kmcervan — APPROVED** [review]
Simple change, looks good.

**Review by bharukimiller — APPROVED** [review]
Changes make sense, nothing complicated. Good eye though!

**Review by elCarlosSantiago — APPROVED** [review]
Straightforward!

**Pull request merged**
