### PR TITLE
Bugfix/navbar logo alignment

### PR DESCRIPTION
**Pull request by ctscofield**
## Description

Earlier today 9/23/2021 in the product review meeting Frank asked Will Moon and I to move the HRF-logo to line up with the icons from the collapsing sidebar. And we did so.

[Loom](https://www.loom.com/share/16b0b32702d24b788ae022478f1a4174)
[Trello](https://trello.com/c/BtmVBtgb)

Co-authored-by: @willmoon19 

## Type of change
Styling

- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have removed unnecessary comments/console logs from my code
- [x] My changes generate no new warnings
- [x] I have checked my code and corrected any misspellings
- [x] No duplicate code left within changed files
- [x] Size of pull request kept to a minimum
- [x] Pull request description clearly describes changes made & motivations for said changes

### CODE REVIEW

**Review by willmoon19 — APPROVED** [review]
small adjustment that makes the header look much more balanced

**Review by AD9018 — APPROVED** [review]
Small change for a great cause!

**Comment by Vehmeyer** [comment]
Nice to see the header logo and sidebar icons in alignment. Looks more polished. Nice work!

**Review by Vehmeyer — APPROVED** [review]
Nice to see the header logo and sidebar icons in alignment. Looks more polished. Nice work!

**Pull request merged**
