### PR TITLE
Fixing MUI buttons

### PR DESCRIPTION
**Pull request by JusticeMatthew**

### CODE REVIEW

**Review by c-melchor — APPROVED** [review]
🥳  Thanks for this fix, it'll be nice to see our text again

**Review by crystal-csete — APPROVED** [review]
Nice fix for the buttons.

**Review by ruizaj13 — APPROVED** [review]
Buttons, we need buttons to do button things.

**Review by ndossett — APPROVED** [review]
Glad we were able to find the fix for this relatively quickly. Thanks for always leading the troubleshooting!

**Pull request merged**
