### PR TITLE
moved css to its own file

### PR DESCRIPTION
**Pull request by crystal-csete**
I moved CSS from the case table into its own file.
I will add in Juan's fixes for the drawer, I have the specs still.

### CODE REVIEW

**Review by cmirza — APPROVED** [review]
Good update to keeping styling organized

**Review by reesharper — APPROVED** [review]
This will clean up the functional components a ton! Love how readable this makes the code

**Review by JusticeMatthew — APPROVED** [review]
More separation of concerns Love it

**Review by ndossett — APPROVED** [review]
This is great for cleaner case file and have more streamlined styling throughout the app

**Review by aydinsenih — APPROVED** [review]
nice changes to keep code organized

**Pull request merged**
