### PR TITLE
Updated the case table structure to match the backend changes

### PR DESCRIPTION
**Pull request by JusticeMatthew**
Finally, this overhaul is complete!

The cases table is the first example and now takes advantage of our tagging system and correctly renders initial and appellate cases separately

### CODE REVIEW

**Review by c-melchor — APPROVED** [review]
Matthew, nicely done!! I know this was a long time coming.

**Review by crystal-csete — APPROVED** [review]
Great job on matching the new table names front end to back end.

**Review by ndossett — APPROVED** [review]
Nice work! This is a major addition as now we can have our components render correctly to the screen.

**Review by reesharper — APPROVED** [review]
Updating these naming conventions is a pain thank you for killing it on this!

**Review by ruizaj13 — APPROVED** [review]
Glad to see the tab functionality is working

**Pull request merged**
