### PR TITLE
Add period to end of first paragraph in “Getting Started” section of …

### PR DESCRIPTION
**Pull request by Vehmeyer**
…README file to maintain consistent punctuation. Fix spelling errors in “Still Needs Work” section.

## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] This change requires a documentation update

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have removed unnecessary comments/console logs from my code
- [x] I have made corresponding changes to the documentation if necessary (optional)
- [x] My changes generate no new warnings
- [x] I have checked my code and corrected any misspellings
- [x] No duplicate code left within changed files
- [x] Size of pull request kept to a minimum
- [x] Pull request description clearly describes changes made & motivations for said changes

https://www.loom.com/share/bfc5d9f1753440b3b7cbc171dbd471b4

### CODE REVIEW

**Review by iwood55 — APPROVED** [review]
John fixed spelling issues in the readme.

**Review by mariuscmoldovan — APPROVED** [review]
Nice catch. Seems good to me.

**Review by ivan-mihailov — APPROVED** [review]
Good catch on the spelling mistakes. ReadMe is usually the first file devs and stakeholders read so it is important that it is professional and as error-free as possible.

**Review by RasmussenBen — APPROVED** [review]
Thanks, John. The ongoing battle against the original syntax errors.

**Review by AZICO — APPROVED** [review]
Great work catching on punctuation!

**Pull request merged**
