### PR TITLE
Feature/consistent hearder styling

### PR DESCRIPTION
**Pull request by secoyawood**
## Description
Contributors: @dylan-rinella 

[Trello](https://trello.com/c/YPoGCqUy)
[Loom OTW](https://www.loom.com/share/5382b70ee5c743d1a15c375e5c30e892)

This PR aims to make headers on all pages consistent. First off the "My Cases" page was absent of a header so that was added. Next, the "Cases" had a header that was centered with the entire page, not taking into account the left navbar such as the "Home" or "Judges" pages. The "Home" page was given a longer orange bar to match the rest of the pages for overall consistency.

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have removed unnecessary comments/console logs from my code
- [x] I have made corresponding changes to the documentation if necessary (optional)
- [x] My changes generate no new warnings
- [x] I have checked my code and corrected any misspellings
- [x] No duplicate code left within changed files
- [x] Size of pull request kept to a minimum
- [x] Pull request description clearly describes changes made & motivations for said changes

### CODE REVIEW

**Review by AD9018 — APPROVED** [review]
Changes seem sound. Good progress!

**Review by willmoon19 — COMMENTED** [review]
Looks good! I think it will really help us too when we go to adjust the side drawer. Clean code, well done!

**Review by leecrowe — APPROVED** [review]
It looks like some simple changes were made, but they seem overall needed and useful, nice work

**Comment by secoyawood** [comment]
> 
> 
> Looks good! I think it will really help us too when we go to adjust the side drawer. Clean code, well done!

I see you edited your comment but I wanted to respond to the point you brought up! There was not much testing for the different screen sizes during this PR because the entire application needs a lot of work for the resizing aspect. We felt that it wouldn't make sense for the scope of this ticket to only have the header resize appropriately when smaller or bigger when everything else breaks. Hope this makes sense, but it was an excellent point to bring up :)

**Review by ctscofield — APPROVED** [review]
I like how you took the time to make the styling consistent across the different pages!

**Comment by Vehmeyer** [comment]
Nice update! Good to see consistent styling among the components.

**Review by Vehmeyer — APPROVED** [review]
Nice update! Good to see consistent styling among the components.

**Review by RasmussenBen — APPROVED** [review]
Great changes, Secoya! These small UI changes really add up to making the app feel professional and polished. Extending styling baselines to new components is a constant battle and something easily overlooked. I also appreciated being shown the clear before-and-after in your Loom video.

**Review by ivan-mihailov — APPROVED** [review]
Loom video was very helpful walking us through the visual changes. The addition of My Cases is important both from a visual and consistency standpoint as the user will likely spend a lot of time on that page and will need to be able to easily navigate to/from it. The code changes look good. Great Job!

**Review by AZICO — COMMENTED** [review]
Small yet important changes you have made to the style of the web app, in addition to documenting it well. Great job!

**Review by sirakisaias — APPROVED** [review]
Great job secoyaw, as a UX engineer in this lab I know how important the small changes to the site make a very big difference. The changes you made using rem and % on margin, padding, and border looks good; and it is with the standards of responsive design

**Pull request merged**
